# -*- coding: utf-8 -*-
"""Session1_PDF_to_Chunks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_LWvo6O1RTEQxp1pqe-fSnHZytYXysy
"""

!pip install pymupdf pdfplumber

import fitz
import pdfplumber

from google.colab import files

uploaded = files.upload()

pdf_path = next(iter(uploaded))
print(pdf_path)

import fitz

doc = fitz.open(pdf_path)

print("Nombre de pages :", len(doc))

text_total = ""
for page in doc:
    text_total += page.get_text()

print("Nombre total de caractères :", len(text_total))
print("Moyenne de caractères par page :", len(text_total) / len(doc))

def nettoyer(texte):
    texte = texte.replace("’", "'")
    texte = texte.replace("\x00", "")
    texte = texte.replace("-\n", "")
    texte = texte.replace("\n", " ")
    texte = " ".join(texte.split())
    return texte


blocs = []

for num_page, page in enumerate(doc):
    page_dict = page.get_text("dict")

    for block in page_dict["blocks"]:
        if "lines" not in block:
            continue

        for line in block["lines"]:
            spans = line["spans"]

            texte_ligne = ""
            tailles = []

            for span in spans:
                texte_ligne += span["text"]
                tailles.append(span["size"])

            texte_ligne = nettoyer(texte_ligne)

            if texte_ligne:
                blocs.append({
                    "page": num_page + 1,
                    "texte": texte_ligne,
                    "taille_police": max(tailles)
                })

print("Nombre de blocs extraits :", len(blocs))

from collections import Counter

compteur_tailles = Counter(
    round(bloc["taille_police"], 1)
    for bloc in blocs
)

print("Tailles de police les plus fréquentes :")

for taille, nombre in compteur_tailles.most_common(15):
    print(f"{taille} : {nombre}")

tailles_titres = sorted(
    [taille for taille in compteur_tailles if taille > 10],
    reverse=True
)

print("Tailles de police supérieures à 10 :")
print(tailles_titres)

for bloc in blocs:
    if bloc["taille_police"] >= 17:
        print(
            f'Page {bloc["page"]} | '
            f'Taille {bloc["taille_police"]} | '
            f'{bloc["texte"][:150]}'
        )

taille_corps = compteur_tailles.most_common(1)[0][0]

print("Taille de police du corps :", taille_corps)

import re

def nettoyer(texte):
    """Normalise le texte extrait d'un PDF."""
    texte = texte.replace("\u2019", "'")
    texte = "".join(ch for ch in texte if ch.isprintable() or ch == " ")
    texte = re.sub(r"(\w)-\s+(\w)", r"\1\2", texte)
    return re.sub(r"\s+", " ", texte).strip()


lignes = []

for num_page, page in enumerate(doc, start=1):
    for bloc in page.get_text("dict")["blocks"]:
        if bloc.get("type") != 0:
            continue

        for ligne in bloc["lines"]:
            spans = ligne["spans"]
            texte = nettoyer("".join(s["text"] for s in spans))

            if texte:
                lignes.append({
                    "page": num_page,
                    "texte": texte,
                    "taille": max(round(s["size"], 1) for s in spans),
                })

print(f"{len(lignes)} lignes extraites\n")

for l in lignes[:5]:
    print(f"  p.{l['page']:>2}  {l['taille']:>5.1f}pt  {l['texte'][:58]}")

for l in lignes[800:806]:
    print(f"  p.{l['page']:>2}  {l['taille']:>5.1f}pt  {l['texte'][:58]}")

taille_corps = Counter(l["taille"] for l in lignes).most_common(1)[0][0]

tailles_titres = sorted(
    {l["taille"] for l in lignes if l["taille"] >= taille_corps * 1.3},
    reverse=True
)

niveau_de = {taille: rang for rang, taille in enumerate(tailles_titres)}

print(f"Corps du texte : {taille_corps} pt")
print(f"Niveaux de titres : {tailles_titres}\n")

propres = []

for ligne in lignes:
    # Numero de page isole, ou note de bas de page : on jette.
    if ligne["texte"].isdigit() or ligne["taille"] < taille_corps * 0.85:
        continue

    # Un titre est plus gros que le corps ET court.
    ligne["niveau"] = (
        niveau_de.get(ligne["taille"])
        if len(ligne["texte"]) < 120 else None
    )

    propres.append(ligne)

print(f"{len(propres)} lignes conservees")

lignes = []

for ligne in propres:
    prec = lignes[-1] if lignes else None

    if (
        prec
        and prec["niveau"] is not None
        and ligne["niveau"] == prec["niveau"]
        and ligne["page"] == prec["page"]
    ):
        prec["texte"] += " " + ligne["texte"]
    else:
        lignes.append(ligne)

titres = [l for l in lignes if l["niveau"] is not None]

print(f"{len(lignes)} lignes conservees, dont {len(titres)} titres\n")

print("Extrait de la structure detectee :\n")

for t in titres[:12]:
    print("   " * t["niveau"] + t["texte"][:62])

def table_en_markdown(table):
    """Transforme un tableau brut en texte markdown lisible."""

    grille = [
        [(cellule or "").replace("\n", " ").strip() for cellule in rangee]
        for rangee in table
    ]

    largeur = max(len(r) for r in grille)
    grille = [
        r + [""] * (largeur - len(r))
        for r in grille
    ]

    entete = "| " + " | ".join(grille[0]) + " |"
    separateur = "| " + " | ".join(["---"] * largeur) + " |"
    corps = [
        "| " + " | ".join(r) + " |"
        for r in grille[1:]
    ]

    return "\n".join([entete, separateur] + corps)

tableaux = []

with pdfplumber.open(pdf_path) as pdf:
    for num_page, page in enumerate(pdf.pages, start=1):
        for table in page.extract_tables():

            if table and len(table) >= 3 and max(len(r) for r in table) >= 2:
                tableaux.append({
                    "page": num_page,
                    "markdown": table_en_markdown(table),
                })

print(f"{len(tableaux)} tableaux extraits\n")

for t in tableaux:
    print(
        f"  page {t['page']:>3} : "
        f"{t['markdown'].count(chr(10)) - 1} lignes"
    )

if tableaux:
    print("\nExemple :\n")
    print(tableaux[0]["markdown"][:420])