# -*- coding: utf-8 -*-
"""Session2_vectorisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QC-JcuycrOu2aRMk_ohXn6ev7OA6bp4c
"""

!pip install -q "sentence-transformers>=3.0" "faiss-cpu>=1.8"

import json
import re
import sys
import time

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

from pathlib import Path

# =============================================================================
# CHEMINS
# =============================================================================

RACINE = Path.cwd()

CHUNKS = RACINE / "chunks.jsonl"
INDEX = RACINE / "index.faiss"
METADONNEES = RACINE / "chunks.json"


# =============================================================================
# MODELE
# =============================================================================

MODELE = "paraphrase-multilingual-MiniLM-L12-v2"

# Important : le modele est configure par defaut a 128 tokens.
# Nous le montons a 512 comme dans le code de l'instructeur.
LONGUEUR_MAX = 512

# Nombre de chunks encodes en meme temps
TAILLE_LOT = 32


# =============================================================================
# RECHERCHE
# =============================================================================

N_RESULTATS = 3


print("Configuration Session 2")
print("-" * 50)
print(f"Chunks      : {CHUNKS}")
print(f"Index       : {INDEX}")
print(f"Metadonnees : {METADONNEES}")
print(f"Modele      : {MODELE}")
print(f"Max tokens  : {LONGUEUR_MAX}")
print(f"Taille lot  : {TAILLE_LOT}")
print(f"Resultats   : {N_RESULTATS}")

from google.colab import files

uploaded = files.upload()

from pathlib import Path

CHUNKS = Path("chunks.jsonl")

if CHUNKS.exists():
    print("OK : chunks.jsonl est present.")
    print(f"Taille : {CHUNKS.stat().st_size / 1000:.0f} Ko")
else:
    print("ERREUR : chunks.jsonl est introuvable.")

def charger_chunks(chemin):
    """Lit le fichier JSONL : une ligne = un chunk."""

    if not chemin.exists():
        print(f"ERREUR : {chemin} est introuvable.")
        sys.exit(1)

    chunks = []

    with open(chemin, encoding="utf-8") as fichier:
        for ligne in fichier:
            ligne = ligne.strip()

            if ligne:
                chunks.append(json.loads(ligne))

    return chunks


chunks = charger_chunks(CHUNKS)

print(f"{len(chunks)} chunks lus depuis {CHUNKS.name}")

print(json.dumps(chunks[0], indent=2, ensure_ascii=False))

print(f"Chargement du modele : {MODELE}")
print("(Le premier lancement peut telecharger environ 470 Mo.)")

modele = SentenceTransformer(MODELE)

print("\nModele charge.")
print(f"Capacite actuelle : {modele.max_seq_length} tokens")

def verifier_longueurs(chunks, modele):
    """Compare la taille des chunks a la capacite du modele."""

    capacite = modele.max_seq_length

    tailles = [
        c["metadata"].get("n_tokens", 0)
        for c in chunks
    ]

    depassent = sum(
        1 for t in tailles
        if t > capacite
    )

    print(f"  Capacite du modele : {capacite} tokens")
    print(f"  Chunk le plus long : {max(tailles)} tokens")
    print(
        f"  Mediane            : "
        f"{sorted(tailles)[len(tailles) // 2]} tokens"
    )

    if depassent:
        part = depassent / len(chunks) * 100

        print(
            f"\n  ATTENTION : {depassent} chunks sur "
            f"{len(chunks)} ({part:.0f} %) depassent "
            f"la capacite."
        )

        print("  Ils seraient coupes, et la fin du texte perdue.")

    else:
        print("\n  Tous les chunks tiennent dans le modele.")

    return depassent


depassent = verifier_longueurs(chunks, modele)

modele.max_seq_length = LONGUEUR_MAX

print(
    f"max_seq_length porte a "
    f"{modele.max_seq_length} tokens."
)

print(f"Nouvelle capacite du modele : {modele.max_seq_length} tokens")

depassent_apres = verifier_longueurs(chunks, modele)

textes = [c["texte"] for c in chunks]

print(f"Nombre de textes à vectoriser : {len(textes)}")

print("Exemple du premier texte :")
print(textes[0][:500])

debut = time.time()

vecteurs = modele.encode(
    textes,
    batch_size=TAILLE_LOT,
    show_progress_bar=True,
    normalize_embeddings=True,
)

vecteurs = np.asarray(vecteurs, dtype="float32")

print(f"\nVectorisation terminée en {time.time() - debut:.1f} secondes")
print(f"Forme des vecteurs : {vecteurs.shape}")

normes = np.linalg.norm(vecteurs, axis=1)

print(f"Norme moyenne : {normes.mean():.4f}")
print(f"Norme minimale : {normes.min():.4f}")
print(f"Norme maximale : {normes.max():.4f}")

if np.allclose(normes, 1.0, atol=1e-5):
    print("OK : les vecteurs sont normalisés.")
else:
    print("ATTENTION : les vecteurs ne sont pas tous normalisés.")

dimension = vecteurs.shape[1]

index = faiss.IndexFlatIP(dimension)
index.add(vecteurs)

print(f"Nombre de vecteurs dans FAISS : {index.ntotal}")
print(f"Dimension : {index.d}")

faiss.write_index(index, str(INDEX))

print(f"Index sauvegardé : {INDEX}")

with open(METADONNEES, "w", encoding="utf-8") as f:
    json.dump(chunks, f, ensure_ascii=False, indent=2)

print(f"Chunks sauvegardés : {METADONNEES}")

print("=== VERIFICATION ===")
print(f"Chunks        : {len(chunks)}")
print(f"Vecteurs      : {index.ntotal}")
print(f"Dimensions    : {index.d}")
print(f"Index existe  : {INDEX.exists()}")
print(f"Chunks existe : {METADONNEES.exists()}")

if index.ntotal == len(chunks):
    print("\nOK : chaque chunk possède un vecteur.")
else:
    print("\nERREUR : le nombre de chunks et de vecteurs ne correspond pas.")

# On prend un chunk au milieu du corpus
position_test = len(chunks) // 2
texte_test = chunks[position_test]["texte"]

# On vectorise ce même texte
vecteur_test = modele.encode(
    [texte_test],
    normalize_embeddings=True
)

vecteur_test = np.asarray(vecteur_test, dtype="float32")

# Recherche dans FAISS
scores, indices = index.search(vecteur_test, 1)

position_retrouvee = int(indices[0][0])
score = float(scores[0][0])

print(f"Position originale : {position_test}")
print(f"Position retrouvée : {position_retrouvee}")
print(f"Score de similarité : {score:.4f}")

if position_test == position_retrouvee:
    print("OK : le chunk est correctement retrouvé.")
else:
    print("ATTENTION : le chunk n'a pas été retrouvé.")

def recherche_semantique(question, index, chunks, modele, n=3):
    """
    Recherche les n chunks les plus proches d'une question.
    """

    # Transformer la question en vecteur
    vecteur_question = modele.encode(
        [question],
        normalize_embeddings=True
    )

    vecteur_question = np.asarray(
        vecteur_question,
        dtype="float32"
    )

    # Recherche FAISS
    scores, indices = index.search(
        vecteur_question,
        n
    )

    resultats = []

    for score, indice in zip(scores[0], indices[0]):
        resultats.append({
            "score": float(score),
            "chunk": chunks[int(indice)],
            "position": int(indice)
        })

    return resultats

print("Fonction recherche_semantique créée avec succès.")

print("=== STRUCTURE DU CHUNK ===")
print(resultats[0]["chunk"])

print(f"Question : {question}")
print("\n=== RESULTATS ===")

for i, resultat in enumerate(resultats, 1):

    chunk = resultat["chunk"]
    metadata = chunk.get("metadata", {})

    print(f"\n--- Résultat {i} ---")
    print(f"Score    : {resultat['score']:.4f}")
    print(f"Position : {resultat['position']}")
    print(f"Page     : {metadata.get('page', 'N/A')}")
    print(f"Type     : {metadata.get('type', 'N/A')}")
    print(f"Chemin   : {metadata.get('chemin', 'N/A')}")
    print()
    print(chunk["texte"][:1000])

question = "What is finance?"

resultats = recherche_semantique(
    question,
    index,
    chunks,
    modele,
    n=3
)

print(f"Question : {question}")
print("\n=== RESULTATS ===")

for i, resultat in enumerate(resultats, 1):

    chunk = resultat["chunk"]
    metadata = chunk.get("metadata", {})

    print(f"\n--- Résultat {i} ---")
    print(f"Score    : {resultat['score']:.4f}")
    print(f"Position : {resultat['position']}")
    print(f"Page     : {metadata.get('page', 'N/A')}")
    print(f"Type     : {metadata.get('type', 'N/A')}")
    print(chunk["texte"][:700])

questions_test = [
    "What is finance?",
    "What is the time value of money?",
    "What is the relationship between risk and return?",
    "What are financial statements?"
]

for question in questions_test:

    resultats = recherche_semantique(
        question,
        index,
        chunks,
        modele,
        n=3
    )

    print("\n" + "=" * 80)
    print(f"QUESTION : {question}")
    print("=" * 80)

    for i, resultat in enumerate(resultats, 1):

        chunk = resultat["chunk"]
        metadata = chunk.get("metadata", {})

        print(
            f"\n{i}. "
            f"Score={resultat['score']:.4f} | "
            f"Position={resultat['position']} | "
            f"Page={metadata.get('page', 'N/A')}"
        )

        print(chunk["texte"][:400].replace("\n", " "))
        print("...")

question = "What is finance?"

resultats = recherche_semantique(
    question,
    index,
    chunks,
    modele,
    n=N_RESULTATS
)

print("=" * 80)
print(f"QUESTION : {question}")
print("=" * 80)

for i, resultat in enumerate(resultats, 1):

    chunk = resultat["chunk"]
    metadata = chunk.get("metadata", {})

    print(f"\n--- Résultat {i} ---")
    print(f"Score    : {resultat['score']:.4f}")
    print(f"Position : {resultat['position']}")
    print(f"Page     : {metadata.get('page', 'N/A')}")
    print(f"Type     : {metadata.get('type', 'N/A')}")
    print(f"Chemin   : {metadata.get('chemin', 'N/A')}")
    print(f"\n{chunk['texte'][:800]}")

print("=" * 65)
print("             CHECKPOINT FINAL — SESSION 2")
print("=" * 65)

print(f"Nombre de chunks        : {len(chunks)}")
print(f"Nombre de vecteurs      : {index.ntotal}")
print(f"Dimension des vecteurs  : {index.d}")
print(f"Modèle                  : {MODELE}")
print(f"Max sequence length     : {modele.max_seq_length}")
print(f"Batch size              : {TAILLE_LOT}")
print(f"Nombre de résultats     : {N_RESULTATS}")

print("\nFichiers :")
print(f"  index.faiss            : {INDEX.exists()}")
print(f"  chunks.json            : {METADONNEES.exists()}")

print("\nVérification :")

if len(chunks) == index.ntotal:
    print("  ✓ Nombre de chunks = nombre de vecteurs")
else:
    print("  ✗ Problème : chunks ≠ vecteurs")

if INDEX.exists():
    print("  ✓ index.faiss sauvegardé")
else:
    print("  ✗ index.faiss absent")

if METADONNEES.exists():
    print("  ✓ chunks.json sauvegardé")
else:
    print("  ✗ chunks.json absent")

print("\n" + "=" * 65)
print("SESSION 2 TERMINÉE")
print("=" * 65)

from google.colab import files

print("Téléchargement de index.faiss...")
files.download("index.faiss")

print("Téléchargement de chunks.json...")
files.download("chunks.json")